### ISSUE TITLE
unable to get different dates with FuzzyDateTime

### ISSUE THREAD

**Issue by jdh13** [rbarrois/factory_boy#199] opened 2015-04-21 17:00 UTC
Hello,
In Django tests, i have 

```python
class EventFactory(factory.django.DjangoModelFactory):
    ...
    dtstart = FuzzyDateTime(datetime.datetime(2008, 1, 1, tzinfo=UTC), datetime.datetime(2009, 1, 1, tzinfo=UTC),
                        force_hour=10,
                        force_minute=30,
                        force_second=0, force_microsecond=0).evaluate(2, None, False)
```

and i use it:
```
self.event = EventFactory.create()
self.event2 = EventFactory.create()
self.event3 = EventFactory.create()
```

Displaying the resulting dtstart, i got:
dtstart: "2008-07-21 10:30:00+00:00"
dtstart: "2008-07-21 10:30:00+00:00"
dtstart: "2008-07-21 10:30:00+00:00"
The dates are the same, that's not what i expect.

What i don't understand is when i try it in python shell, everytime i call FuzzyDateTime(...), the rresult is always different.

Am i missing something?

thanks in advance for help,

gerard

**Comment by rbarrois** [comment] 2015-04-22 07:59
Hi,

The problem is in your use of ``FuzzyDateTime.evaluate()``: ``evaluate()`` is called by factory_boy's internals, this is what generates a new date.

Your code is equivalent to:
```python
fuzzy_dt = FuzzyDateTime(
    datetime.datetime(2008, 1, 1, tzinfo=UTC),
    datetime.datetime(2009, 1, 1, tzinfo=UTC),
    force_hour=10,
    force_minute=30,
    force_second=0,
    force_microsecond=0
).evaluate(2, None, False)
# fuzzy_dt == datetime.datetime(2008, 7, 21, 10, 30)

class EventFactory(factory.Factory):
    dtstart = fuzzy_dt
```

When you declare a class, Python works as follows:
- First, it evaluates the right-hand side of each ``attribute_name = value`` pair in the class declaration
- Then, it passes those ``(attribute_name, value)`` pairs to the class definition.

Here, you're calling ``.evaluate()`` that returns an actual ``datetime.datetime`` instance instead of a generator.

=> You should remove the ``.evaluate()`` part.

Since ``.evaluate()`` was never intended to be used in ``Factory`` declarations, could you point me to the place you got the idea from? This is likely a bad documentation on my side :)


Thanks,

**Comment by jdh13** [comment] 2015-04-23 17:20
i found it here:
https://factoryboy.readthedocs.org/en/latest/fuzzy.html?highlight=fuzzydatetime#factory.fuzzy.FuzzyDateTime
and i used it as i was unable to obtain the datetimes i'm interested on.

In my project, i need to get a tuple of (start_dt, end_dt). Now, with your help, i can obtain start_dt, but how can i have end_dt as the result of start_dt+1hour?

thanks for your reply,

**Comment by jdh13** [comment] 2015-04-23 17:40
don't you think that, instead of generate random dates beetween limits, we could better have a sequence of datetimes, for instance:
EventFactory.create_batch(N, start_dt, period)
giving start_dt, start_dt+period, ... start_dt+N*period?
as in  .Sequence()?

**Comment by rbarrois** [comment] 2015-04-25 15:23
Hi,

To get a ``end_dt``, simply do the following:

```python
class MyFactory(factory.Factory):
    start_dt = factory.fuzzy.FuzzyDateTime(
        datetime.datetime(2008, 1, 1, tzinfo=UTC),
        datetime.datetime(2009, 1, 1, tzinfo=UTC),
    )
    end_dt = factory.LazyAttribute(lambda o: o.start_dt + datetime.timedelta(hours=1))
```

As to the sequence, this is easy to design by overriding the rule for ``start_dt`` when calling ``create_batch``:

```python
EventFactory.create_batch(N,
     start_dt=factory.Sequence(lambda n: start_dt + datetime.timedelta(hours=n)),
)
```

**Comment by rbarrois** [comment] 2015-10-20 21:50
Hi,

I'm closing this issue for now; feel free to re-open it if you need more help on this topic!

**Closed by rbarrois** 2015-10-20 21:50 UTC
Labels: Doc, Q&A
